version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/db_delivery
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - receita.jwt.secret=1234554321
      - receita.jwt.expiration=86400000
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

    depends_on:
      - mysqldb
    restart: unless-stopped
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_delivery
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
